//! PostgreSQL-backed account storage: users, sessions, and aircraft
//! records (DESIGN.md §9.5).
//!
//! This is the first thing `freeflight` writes. Everything else the
//! server holds is either derived from an upstream source (`ff-etl`'s
//! cycle bundles) or proxied live (weather, NOTAMs), and can be
//! regenerated by re-running a job. What lands here — a pilot's fleet and
//! the performance numbers they typed out of a POH — cannot. That is the
//! reason it lives in a real database with a backup job rather than in a
//! browser's localStorage.
//!
//! ## Why a second database, and a second engine
//!
//! [`ff-storage`](../ff_storage/index.html) already exists and is
//! SQLite. It is not reusable here: it describes the *cycle bundle*,
//! which `ff-etl` republishes wholesale every AIRAC cycle — user rows
//! kept alongside it would be destroyed every 28 days — and it is headed
//! for the Android native library (§8), where a Postgres driver would be
//! dead weight. Different data, different lifecycle, different crate.
//!
//! ## Queries are runtime-checked, not `query!`-macro checked
//!
//! `sqlx` is used through [`sqlx::query`]/[`sqlx::query_as`] rather than
//! its compile-time-checked macros. The macros need either a reachable
//! database at build time or a committed `.sqlx` metadata directory kept
//! in sync by hand; `deploy/Dockerfile` builds with neither, and
//! `cargo check --workspace` must keep working for anyone without a
//! Postgres. Schema drift is caught by the integration tests instead,
//! which run the real migrations against a real server.
//!
//! Migrations are embedded at compile time (no database needed to
//! *build*) and applied on [`Accounts::open`].

mod aircraft;
mod sessions;

pub use aircraft::{Aircraft, AircraftDetail, AircraftInput, PerformanceRow, Phase};
pub use sessions::StoredUser;

use sqlx::migrate::Migrator;
use sqlx::postgres::{PgPool, PgPoolOptions};
use std::time::Duration;
use thiserror::Error;

/// Embedded at compile time from `migrations/`, applied in version order
/// with `sqlx`'s advisory lock so two containers starting at once cannot
/// double-apply. Forward-only: a bad migration is corrected by shipping
/// another one, not by rolling back (§9.5.8).
static MIGRATOR: Migrator = sqlx::migrate!("./migrations");

/// How long to wait for a connection from the pool before giving up.
/// Short on purpose: a request that cannot get a connection should fail
/// fast and let the caller report the feature as unavailable, rather than
/// stacking up behind a database that is gone.
const ACQUIRE_TIMEOUT: Duration = Duration::from_secs(5);

/// Small pool — one modest container, a handful of rows per user, and a
/// Postgres shared with the other apps on the host. There is no workload
/// here that benefits from holding many connections open.
const MAX_CONNECTIONS: u32 = 5;

#[derive(Debug, Error)]
pub enum AccountsError {
    #[error("database error: {0}")]
    Sqlx(#[from] sqlx::Error),
    #[error("migration failed: {0}")]
    Migrate(#[from] sqlx::migrate::MigrateError),
}

impl AccountsError {
    /// True when the write lost a race against a uniqueness rule — a
    /// second aircraft with the same registration, say. Callers map this
    /// to "409 Conflict"; everything else is a server-side failure.
    ///
    /// Exposed here rather than having HTTP handlers match on
    /// `sqlx::Error` so that the storage engine stays behind this crate's
    /// API — nothing above it should need to know what SQLSTATE 23505
    /// is.
    pub fn is_unique_violation(&self) -> bool {
        match self {
            AccountsError::Sqlx(sqlx::Error::Database(db)) => db.code().as_deref() == Some("23505"),
            _ => false,
        }
    }
}

/// A handle on the account database: a connection pool plus the schema
/// it is expected to have. Cheap to clone (the pool is internally
/// reference-counted), so it can be held in `ff-api`'s `AppState`.
#[derive(Clone)]
pub struct Accounts {
    pool: PgPool,
}

impl Accounts {
    /// Connect to `database_url` and bring the schema up to date.
    ///
    /// Mirrors `ff_storage::open`'s connect-and-migrate shape so the two
    /// storage crates behave the same way. Connecting is lazy in `sqlx`,
    /// so the migration is also what proves the database is actually
    /// reachable and the credentials work — this returns `Err` rather
    /// than deferring the failure to the first query.
    ///
    /// The caller decides what a failure means. `ff-api` treats account
    /// storage as optional (`FF_DATABASE_URL` unset disables it), and an
    /// unreachable database must not stop the map/weather/planning
    /// endpoints from serving.
    pub async fn open(database_url: &str) -> Result<Self, AccountsError> {
        let pool = PgPoolOptions::new()
            .max_connections(MAX_CONNECTIONS)
            .acquire_timeout(ACQUIRE_TIMEOUT)
            .connect(database_url)
            .await?;
        let accounts = Self { pool };
        accounts.migrate().await?;
        Ok(accounts)
    }

    /// Apply any outstanding migrations. Idempotent — already-applied
    /// versions are skipped, and `sqlx` verifies the checksum of each one
    /// it has seen before, so an edited migration fails loudly instead of
    /// silently diverging from what production ran.
    pub async fn migrate(&self) -> Result<(), AccountsError> {
        MIGRATOR.run(&self.pool).await?;
        Ok(())
    }

    /// Round-trip the database, for a health endpoint or a startup check.
    pub async fn ping(&self) -> Result<(), AccountsError> {
        sqlx::query("SELECT 1").execute(&self.pool).await?;
        Ok(())
    }

    /// The underlying pool, for the query modules added in later steps
    /// (§9.5.10 steps 2 and 3).
    pub fn pool(&self) -> &PgPool {
        &self.pool
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::{Duration as ChronoDuration, Utc};

    /// Integration tests need a real PostgreSQL — the whole point is to
    /// check constraints the engine enforces, which no mock reproduces.
    /// They are skipped rather than failed when one isn't configured, so
    /// `cargo test` stays green on a machine with no database:
    ///
    /// ```text
    /// docker run -d --name ff-pg-test -e POSTGRES_PASSWORD=devpass \
    ///     -e POSTGRES_DB=freeflight -p 55432:5432 postgres:18
    /// FF_TEST_DATABASE_URL=postgres://postgres:devpass@localhost:55432/freeflight \
    ///     cargo test -p ff-accounts
    /// ```
    async fn accounts() -> Option<Accounts> {
        let url = match std::env::var("FF_TEST_DATABASE_URL") {
            Ok(url) if !url.is_empty() => url,
            _ => {
                eprintln!("skipping: FF_TEST_DATABASE_URL not set");
                return None;
            }
        };
        Some(Accounts::open(&url).await.expect("open test database"))
    }

    // Every data test below runs inside a transaction that is never
    // committed, so it rolls back on drop and leaves the database exactly
    // as found — which also makes the suite safe to point at a shared
    // server.

    /// Asserts that `sql` is refused by the schema.
    ///
    /// Postgres aborts the *entire* transaction on any statement error,
    /// and every later statement then fails with 25P02 regardless of its
    /// own merits. A test that deliberately violates a constraint and
    /// then keeps going therefore has to fence each attempt in a
    /// savepoint — without this, a run of "these should all be rejected"
    /// assertions passes even when only the first constraint exists,
    /// which is exactly the false green this helper was written to fix.
    async fn rejects(
        tx: &mut sqlx::PgConnection,
        label: &str,
        sql: &str,
        aircraft_id: Option<i64>,
    ) {
        sqlx::query("SAVEPOINT attempt")
            .execute(&mut *tx)
            .await
            .expect("savepoint");
        let query = sqlx::query(sql);
        let result = match aircraft_id {
            Some(id) => query.bind(id).execute(&mut *tx).await,
            None => query.execute(&mut *tx).await,
        };
        assert!(result.is_err(), "{label} was accepted");
        sqlx::query("ROLLBACK TO SAVEPOINT attempt")
            .execute(&mut *tx)
            .await
            .expect("rollback to savepoint");
    }

    async fn insert_user(tx: &mut sqlx::PgConnection, subject: &str) -> i64 {
        sqlx::query_scalar(
            "INSERT INTO app_user (provider, subject, display_name)
             VALUES ('google', $1, 'Test Pilot') RETURNING id",
        )
        .bind(subject)
        .fetch_one(tx)
        .await
        .expect("insert user")
    }

    #[tokio::test]
    async fn migrations_apply_and_are_idempotent() {
        let Some(accounts) = accounts().await else {
            return;
        };
        // open() already migrated; running again must be a no-op rather
        // than an error, since every container start calls it.
        accounts.migrate().await.expect("re-running migrations");
        accounts.ping().await.expect("ping");

        for table in ["app_user", "session", "aircraft", "aircraft_performance"] {
            let exists: bool = sqlx::query_scalar(
                "SELECT EXISTS (SELECT 1 FROM information_schema.tables
                 WHERE table_schema = 'public' AND table_name = $1)",
            )
            .bind(table)
            .fetch_one(accounts.pool())
            .await
            .expect("query information_schema");
            assert!(exists, "table {table} missing");
        }
    }

    #[tokio::test]
    async fn a_user_is_unique_per_provider_and_subject() {
        let Some(accounts) = accounts().await else {
            return;
        };
        let mut tx = accounts.pool().begin().await.expect("begin");
        insert_user(&mut tx, "subject-unique").await;
        rejects(
            &mut tx,
            "the same identity twice",
            "INSERT INTO app_user (provider, subject, display_name)
             VALUES ('google', 'subject-unique', 'Someone Else')",
            None,
        )
        .await;

        // The same subject from a different provider is a different person.
        sqlx::query(
            "INSERT INTO app_user (provider, subject, display_name)
             VALUES ('discord', 'subject-unique', 'Different Provider')",
        )
        .execute(&mut *tx)
        .await
        .expect("same subject, other provider");
    }

    #[tokio::test]
    async fn registration_must_be_uppercase_and_unique_per_user() {
        let Some(accounts) = accounts().await else {
            return;
        };
        let mut tx = accounts.pool().begin().await.expect("begin");
        let user = insert_user(&mut tx, "subject-reg").await;

        sqlx::query("INSERT INTO aircraft (user_id, registration) VALUES ($1, 'N172SP')")
            .bind(user)
            .execute(&mut *tx)
            .await
            .expect("insert aircraft");

        // Lowercase is refused outright, so it can never become a second
        // aircraft that only differs by case.
        rejects(
            &mut tx,
            "lowercase registration",
            "INSERT INTO aircraft (user_id, registration) VALUES ($1, 'n172sp')",
            Some(user),
        )
        .await;
        rejects(
            &mut tx,
            "duplicate registration",
            "INSERT INTO aircraft (user_id, registration) VALUES ($1, 'N172SP')",
            Some(user),
        )
        .await;

        // ...but another pilot may keep their own record for the same
        // tail number — a shared club aircraft.
        let other = insert_user(&mut tx, "subject-reg-other").await;
        sqlx::query("INSERT INTO aircraft (user_id, registration) VALUES ($1, 'N172SP')")
            .bind(other)
            .execute(&mut *tx)
            .await
            .expect("same registration, different owner");
    }

    #[tokio::test]
    async fn performance_rows_are_constrained_to_real_values() {
        let Some(accounts) = accounts().await else {
            return;
        };
        let mut tx = accounts.pool().begin().await.expect("begin");
        let user = insert_user(&mut tx, "subject-perf").await;
        let aircraft: i64 = sqlx::query_scalar(
            "INSERT INTO aircraft (user_id, registration) VALUES ($1, 'N9999X') RETURNING id",
        )
        .bind(user)
        .fetch_one(&mut *tx)
        .await
        .expect("insert aircraft");

        // A climb row: power_setting defaults to '' (the "not applicable"
        // slot) so it can sit in the primary key.
        sqlx::query(
            "INSERT INTO aircraft_performance
                 (aircraft_id, phase, pressure_altitude_ft, vertical_speed_fpm, tas_kt, fuel_gph)
             VALUES ($1, 'climb', 0, 700, 75, 9.5)",
        )
        .bind(aircraft)
        .execute(&mut *tx)
        .await
        .expect("insert climb row");

        let power: String = sqlx::query_scalar(
            "SELECT power_setting FROM aircraft_performance WHERE aircraft_id = $1 AND phase = 'climb'",
        )
        .bind(aircraft)
        .fetch_one(&mut *tx)
        .await
        .expect("read back");
        assert_eq!(power, "");

        // Two cruise rows at the same altitude but different power
        // settings are distinct rows, not a key collision.
        for setting in ["65%", "75%"] {
            sqlx::query(
                "INSERT INTO aircraft_performance
                     (aircraft_id, phase, pressure_altitude_ft, power_setting, tas_kt, fuel_gph)
                 VALUES ($1, 'cruise', 6000, $2, 110, 7.5)",
            )
            .bind(aircraft)
            .bind(setting)
            .execute(&mut *tx)
            .await
            .expect("insert cruise row");
        }

        // Garbage the planner must never see. Each is fenced in its own
        // savepoint so all four constraints are genuinely exercised —
        // see `rejects`.
        for (label, sql) in [
            (
                "unknown phase",
                "INSERT INTO aircraft_performance (aircraft_id, phase, pressure_altitude_ft, tas_kt, fuel_gph)
                 VALUES ($1, 'loiter', 0, 110, 7.5)",
            ),
            (
                "zero TAS",
                "INSERT INTO aircraft_performance (aircraft_id, phase, pressure_altitude_ft, tas_kt, fuel_gph)
                 VALUES ($1, 'cruise', 1000, 0, 7.5)",
            ),
            (
                "negative fuel burn",
                "INSERT INTO aircraft_performance (aircraft_id, phase, pressure_altitude_ft, tas_kt, fuel_gph)
                 VALUES ($1, 'cruise', 2000, 110, -1)",
            ),
            (
                "absurd altitude",
                "INSERT INTO aircraft_performance (aircraft_id, phase, pressure_altitude_ft, tas_kt, fuel_gph)
                 VALUES ($1, 'cruise', 99000, 110, 7.5)",
            ),
        ] {
            rejects(&mut tx, label, sql, Some(aircraft)).await;
        }
    }

    #[tokio::test]
    async fn a_cg_envelope_must_not_be_inverted() {
        let Some(accounts) = accounts().await else {
            return;
        };
        let mut tx = accounts.pool().begin().await.expect("begin");
        let user = insert_user(&mut tx, "subject-cg").await;
        let inverted = sqlx::query(
            "INSERT INTO aircraft (user_id, registration, forward_cg_limit_in, aft_cg_limit_in)
             VALUES ($1, 'N1CG', 47.3, 35.0)",
        )
        .bind(user)
        .execute(&mut *tx)
        .await;
        assert!(inverted.is_err(), "an inverted CG envelope was accepted");
    }

    #[tokio::test]
    async fn deleting_a_user_removes_everything_they_own() {
        let Some(accounts) = accounts().await else {
            return;
        };
        let mut tx = accounts.pool().begin().await.expect("begin");
        let user = insert_user(&mut tx, "subject-cascade").await;
        let aircraft: i64 = sqlx::query_scalar(
            "INSERT INTO aircraft (user_id, registration) VALUES ($1, 'N5CASC') RETURNING id",
        )
        .bind(user)
        .fetch_one(&mut *tx)
        .await
        .expect("insert aircraft");
        sqlx::query(
            "INSERT INTO aircraft_performance
                 (aircraft_id, phase, pressure_altitude_ft, tas_kt, fuel_gph)
             VALUES ($1, 'cruise', 4000, 110, 7.5)",
        )
        .bind(aircraft)
        .execute(&mut *tx)
        .await
        .expect("insert performance row");
        sqlx::query("INSERT INTO session (token_hash, user_id, expires_at) VALUES ($1, $2, $3)")
            .bind(vec![7u8; 32])
            .bind(user)
            .bind(Utc::now() + ChronoDuration::days(30))
            .execute(&mut *tx)
            .await
            .expect("insert session");

        // One statement is the whole of "delete my data" (§9.5.9).
        sqlx::query("DELETE FROM app_user WHERE id = $1")
            .bind(user)
            .execute(&mut *tx)
            .await
            .expect("delete user");

        for (table, column) in [("aircraft", "user_id"), ("session", "user_id")] {
            let remaining: i64 =
                sqlx::query_scalar(&format!("SELECT count(*) FROM {table} WHERE {column} = $1"))
                    .bind(user)
                    .fetch_one(&mut *tx)
                    .await
                    .expect("count");
            assert_eq!(remaining, 0, "{table} rows survived the user");
        }
        let orphan_rows: i64 =
            sqlx::query_scalar("SELECT count(*) FROM aircraft_performance WHERE aircraft_id = $1")
                .bind(aircraft)
                .fetch_one(&mut *tx)
                .await
                .expect("count performance");
        assert_eq!(orphan_rows, 0, "performance rows survived their aircraft");
    }

    #[tokio::test]
    async fn a_session_token_hash_must_be_a_sha256() {
        let Some(accounts) = accounts().await else {
            return;
        };
        let mut tx = accounts.pool().begin().await.expect("begin");
        let user = insert_user(&mut tx, "subject-session").await;
        // A raw token stored by mistake would be the wrong length; the
        // constraint makes that a loud failure rather than a quiet
        // plaintext-secret-at-rest bug.
        let raw = sqlx::query(
            "INSERT INTO session (token_hash, user_id, expires_at) VALUES ($1, $2, $3)",
        )
        .bind(b"not-a-sha256".to_vec())
        .bind(user)
        .bind(Utc::now() + ChronoDuration::days(1))
        .execute(&mut *tx)
        .await;
        assert!(raw.is_err(), "a non-SHA-256 token_hash was accepted");
    }
}
